name: MotoErgoSum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1218638
title: Southern California Motovlogging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#4B4B4B'
    - '#A3A3A3'
    - '#6E6E6E'
  brandStrength: 0.8888889
  lightness: 0.3046595
  saturation: 0.8189964
  rhythmicContrast: 0.311828
purpose: []
