typography_spectrum: 0.48753
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c2c2c2'
    - '#595959'
    - '#9f9f9f'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/246a98ee-4fa3-442c-99df-07dcdf67741d.png
  type: null
  appId: null
layout_spectrum: 0.60987
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: kuhlka@yahoo.com
  url: 'http://www.motoergosum.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7a6e60d4-e2b3-4015-b06e-be7840c5a539.png
name: MotoErgoSum
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: MES Branded Clothing
    url: 'https://shop.spreadshirt.com/motoergosum/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/motoergosum/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/user/kuhlka'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/motoergosum/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/motoergosum'
    type: external
  - name: Tumblr
    url: 'http://motoergosum.tumblr.com/'
    type: external
  - name: Flikr
    url: 'https://www.flickr.com/photos/72483840@N00/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/02e8b1f9-6433-4b48-b22e-77f3b5973b45.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Moto Ergo Sum
description: Southern California Motovlogging
purpose: []
