typography_spectrum: 0.48753
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c2c2c2'
    - '#595959'
    - '#9f9f9f'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60987
analytics:
  google: null
  facebook: null
  twitter: null
name: MotoErgoSum
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/user/kuhlka'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/motoergosum/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/motoergosum/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/motoergosum'
    type: external
  - name: Tumblr
    url: 'http://motoergosum.tumblr.com/'
    type: external
  - name: Flikr
    url: 'https://www.flickr.com/photos/72483840@N00/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Southern California Motovlogging
purpose: []
